name: Cart

on:
  push:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/cart.yaml'  # Include workflow file changes

  pull_request:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/cart.yaml'  # Include workflow file changes

jobs:
  cart:
    name: Build and deploy cart microservice
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: NPM install
        run: npm install 

      - name: Build Docker image
        run: |
          docker build -t cart .  # Build image tagged as 'cart' from current directory

      - name: Docker Login (use secrets)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    #  - name: Docker Push
    #    run: |
    #      docker tag cart ${name}/cart:latest
    #      docker push ${name}/cart:latest
      
      - name: Docker Push
        run: |
          docker tag cart ${{ secrets.DOCKERHUB_USERNAME }}/rs-cart:${{ github.run_id }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rs-cart:${{ github.run_id }}


  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: cart

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart values.yaml
        run: |
          sed -i 's/^  version: .*/  version: "${{ github.run_id }}"/' helm/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "hossamd512@gmail.com"
          git config --global user.name "hossam-darwish"
          git add helm/values.yaml
          git commit -m "Update Helm chart image version to ${{ github.run_id }}"
          git push

      